### ISSUE TITLE
Export a variable that says if the Job is done

### ISSUE THREAD

**Issue by MarcoVigna17** [ajvb/kala#113]
Is it possible to have a variable in the Job structure, exported with the API call that says if the job has been completed and it shouldn't been executed again in the future?

**Comment by ajvb** [comment]
@MarcoVigna17 No, but it is possible to infer that by looking at the JobStats.

**Comment by benwaine** [comment]
@ajvb Kala is responsible for determining how may times to repeat a job and stores this in the unexported `Job` property `timesToRepeat`. Currently, externally to the package there is nothing that we could compare `JobStats` to in order to determine Job completion.   

Comparing two values published by the API on the client side to determine "completeness"  feels like a leaky abstraction to me. What do you think to the idea of exposing a property that corresponds to `len(JobStats) == j.timesToRepeat`?

This allows the behaviour of that property to change in the future in the event that `complete ==  len(JobStats) == j.timesToRepeat` no long holds true.

**Comment by ajvb** [comment]
@benwaine I like it and I like @MarcoVigna17's implementation.
