### ISSUE TITLE
WebUI returns 404

### ISSUE THREAD

**Issue by frankmoshe** [ajvb/kala#235]
I followed the commands in docs: `go get ....` and then `kala serve`. The API works fine, but when trying http://127.0.0.1:8000/webui it returns _404 page not found_

I'm using Mac OS, so don't know if the install process should be different here.

I've also tried the following: Downloaded the repository and `.make`, then executed `./kala serve` from the bin folder generated. Same problem, not webui working.

Is there any parameter for `kala` to assign the folder for the webui? Maybe `--web /webui`?

**Comment by tooolbox** [comment]
Hey there, let's see if I can help you out.

1. Yikes, looks like the Makefile needs a little work since it's still talking about `GOPATH` and the project now uses Go Modules.
2. Currently, for the dashboard to work, you'll need to run Kala from main directory of the project.  So either `./bin/kala serve` or you can do a straight `go build` and then `./kala serve`.  This is also why a straight `go get ...` doesn't work.
3. There's an open issue (#228) for embedding the dashboard files into the binary, which will resolve this foolishness.  Contributions are welcome 👍 

Recent development was all done on MacOS so no worries there.

**Comment by frankmoshe** [comment]
Thanks!

WebUI worked with the `go build` and `./kala serve` commands. 🚀
