### ISSUE TITLE
Utilize abtime pkg for more precise timing tests

### ISSUE THREAD

**Issue by ajvb** [ajvb/kala#48]
Use [abtime](https://github.com/thejerf/abtime) to be much more specific in my testing of the job scheduling.

**Comment by tooolbox** [comment]
https://github.com/thejerf/abtime will not be used.

This is mainly because I can't understand why you'd want to use it.  The author has explained that normal time-advancing packages are flawed because things might not fire exactly in sequence in a multi-threaded environment.  The proposed solution is to give every timer (and related construct or mechanism) an ID and manually fire them.

For the purpose of testing a *scheduling package* this doesn't make any sense because you want to be able to advance the time by X amount and see that your job ran.  You don't care how many threads are involved.  If you manually fire your timers, you're not testing the relationship of your timers to the passage of time.

My one concept of use case for abtime is if you want to test what happens when two events, which are supposed to happen in a certain sequence, happen in reverse due to the aforementioned multi-threaded shenanigans.  If you want to unit-test what happens in that scenario, great, use abtime--although it seems like it might be a bug to be resolved more than a scenario to be handled gracefully.

(The comments in Kala's source about using abtime were centered around parent/child relationships.  For example, ensuring that multiple child jobs fire in the correct sequence.  In that case, abtime's stack-of-nows would be useful.)

Either way, in the case of Kala we do not care if two jobs that are scheduled at the same time fire in one sequence or another; the main issue is that they *must fire,* and they must do so at the correctly scheduled point.
