### ISSUE TITLE
Add instructions for running a Go function periodically

### ISSUE THREAD

**Issue by elimisteve** [ajvb/kala#72]
Can kala do this, or must the Go function be inside a `main` function in a .go file?  Thanks.

(I see https://github.com/ajvb/kala/blob/master/client/client_test.go but that's still just calling a bash command from Go.)

**Comment by elimisteve** [comment]
Context: I am writing a simple SMS-based app that helps people keep on track with their goals by texting them on certain days per week (initially every day) at the same time on each of those days, and I'm sending those texts via Twilio from Go.  I'd like to use kala to periodically send out those texts.

**Comment by ajvb** [comment]
@elimisteve This is a great use case that I haven't thought of before.

>Can kala do this, or must the Go function be inside a main function in a .go file? Thanks.

Right now, the Go function must be inside a main function in a .go file. I would like to in the future allow for a "Plugin" like architecture within how jobs are ran, so for example you could implement running a Dockerfile (rather than running a bash script that runs a Dockerfile).

For now, I would have a simple CLI where you can pass in the needed info.

Also, please let me know if you have any troubles with deployments and I will be very interested to here how Kala is working for you. Let me know if you have any specific requests, as I prioritize based on what people are asking for :)

**Comment by ajvb** [comment]
@elimisteve I'm going to marked this closed for now. If you it ends up not being, feel free to re-open.
