### ISSUE TITLE
Create a more generic "JobRunner" that will allow for different job types.

### ISSUE THREAD

**Issue by ajvb** [ajvb/kala#73]
Need to flush this out more.

Basic idea is that Kala should be able to support different Job Types, but all of them must be able to be passed to Kala via JSON over HTTP.

A good example of such (taken from Chronos) is the ability to run a container as a job.

---

Some notes:
#### Make JobRunner more generic
1. Change `JobRunner.runCmd()` ( https://github.com/ajvb/kala/blob/master/job/runner.go#L86 ) to something more generic that inspects the Job to figure out what Job type it should run.
2. Add in `JobRunner.runDocker()`
#### Add needed fields to `Job`

Needed Fields:
- `job_type` as proposed by @falschparker82 within #96 
- `container` similar to the field of the same name within Chronos - https://mesos.github.io/chronos/docs/api.html#adding-a-docker-job

**Comment by elimisteve** [comment]
One idea: FWIW, for my use case it would be sufficient (and great) to be able to pass Kala my own function (which whatever signature Kala demands -- perhaps simply `func() error`) that Kala then periodically runs for me.

If you have that, then you could implement a Docker plugin by using the same mechanism, creating a Go function that knows how to run Docker files.  And similarly with other plugins.

**Comment by elimisteve** [comment]
Second idea: for CrypTag, I've created a [Backend interface](https://github.com/elimisteve/cryptag/blob/master/backend/backend.go#L20-L30) that can be satisfied by, say, [a custom FileSystem type](https://github.com/elimisteve/cryptag/blob/master/backend/filesystem.go).

Kala could do something similar, and you would know what those methods should be better than I :-).  Just looking at the core Kala logic that runs jobs and which fields and methods you access on those types, then thinking of how to turn the field accesses into method calls, would probably tell you what the interface definition should be.

But, my first idea above would probably be much more convenient and simpler if it's sufficiently rich to use for a Docker plugin and the like.

**Comment by ajvb** [comment]
>One idea: FWIW, for my use case it would be sufficient (and great) to be able to pass Kala my own function (which whatever signature Kala demands -- perhaps simply func() error) that Kala then periodically runs for me.
>
>If you have that, then you could implement a Docker plugin by using the same mechanism, creating a Go function that knows how to run Docker files. And similarly with other plugins.


@elimisteve I love this.

**Comment by elimisteve** [comment]
@ajvb :-) Either of those designs would work way better for me than what's currently necessary, because right now I'd need to apply command line arguments to a CLI program where one of the arguments -- namely task descriptions they wanted to be reminded of -- is user-specified, and therefore unsafe to supply at the command line; the degree of sanitization I'd have to do to prevent `$HOSTNAME` and "Remind me to `rm -fr ~`" and shit is impractical.

**Comment by ajvb** [comment]
So in discussing this offline, the passing of a `func()` is not needed. Though, this issue is still relevant. It will still all have to be via JSON over HTTP. This could allow for running Docker containers and the like.

**Comment by elimisteve** [comment]
For future readers: @ajvb's (elegant) solution to my problem (described above) was/is to pass to Kala just the ID of the database row containing the info I want texted, so that it can run

    texting_program <row_id>

which my texting program then reads in, does a DB call, then sends the text via Twilio, rather than specifying who the program is texting and what the body of the text message is at the command line, like this:

    texting_program -to <phone_number> -text <user-specified data I was worried might include `rm -fr ~` and the like>

**Comment by tooolbox** [comment]
Closing for now as [remote jobs are now supported](https://github.com/ajvb/kala/pull/139) and this feature will handle many use cases.
